version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rootdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
